version: "3.7"

services:

#####|( o_o)|# Laravel API #|(o_o )|#####

    php:
        build: docker/php/
        container_name: dust_php

        volumes:
            - ./backend:/var/www/backend

        depends_on:
            - db

#####|( o_o)|# Vue SPA #|(o_o )|#####

    node:
        build: docker/node/
        container_name: dust_node

        volumes:
            - ./frontend:/var/www/frontend

        depends_on:
            - php

        ports:
            - "8080:8080"

        environment:
            - HOST=0.0.0.0

#####|( o_o)|# Vue SPA for admin panel #|(o_o )|#####

    admin:
        build: docker/admin/
        container_name: dust_admin

        volumes:
            - ./admin:/var/www/admin

        depends_on:
            - php

        ports:
            - "8081:8081"

        environment:
            - HOST=0.0.0.0

#####|( o_o)|# PostgreSQL #|(o_o )|#####

    db:
        build: docker/db/
        container_name: dust_db

        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
            - ./docker/db/dumps/:/tmp/

        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

        command:
            - "postgres"
            - "-c"
            - "log_statement=all"
            - "-c"
            - "logging_collector=on"

#####|( o_o)|# Redis #|(o_o )|#####

    redis:
        container_name: dust_redis

        build: docker/redis/

        volumes:  
            - redis:/data

        ports:
            - 63791:6379

#####|( o_o)|# Supervisor #|(o_o )|#####

    supervisor:
        container_name: dust_visor

        build: docker/supervisor/

        volumes:
            - ./:/var/www/
            - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
            - ./docker/supervisor/logs:/var/log

        depends_on:
            - db
            - redis

#####|( o_o)|# Nginx #|(o_o )|#####

    nginx:
        build: docker/nginx/
        container_name: dust_nginx

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./backend:/var/www/backend # Backend
            - ./admin:/var/www/admin # Admin panel
            - ./frontend/dist:/var/www/frontend # Static frontend
            - ./docker/nginx/sites:/etc/nginx/sites-enabled
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot 
        
        depends_on:
            - admin
            - node
            - php
            - db

####|( o_o)|# CertBot #|(o_o )####

    certbot:
        image: certbot/certbot  
        container_name: certbot

        volumes: 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot 
        
####|( o_o)|# Volumes #|(o_o )####

volumes:
    database:
        driver: local
    redis:
        driver: local