version: "3.7"

services:

    php:
        build: docker/php/
        container_name: dust_php

        volumes:
            - ./backend:/var/www/backend

        depends_on:
            - db

    db:
        build: docker/db/
        container_name: dust_db

        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
            - ./docker/db/dumps/:/tmp/

        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}


    nginx:
        build: docker/nginx/
        container_name: dust_nginx

        ports:
            - "80:80"

        volumes:
            - ./backend:/var/www/backend
            - ./docker/nginx/sites:/etc/nginx/sites-enabled
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

        depends_on:
            - php
            - db

